### ISSUE TITLE
Optimize the texture cache used for recreating the GL context

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/vrb#22]
The image data is retained so that we can recreate the GL texture when the gl context gets recreated. 
As an optimization we could try to store the path and reload from file/assets when possible (e.g. A 2048 image takes 16MB vs just a string with the path)

**Comment by bluemarvin** [comment]
This only works if the file is local. I hope to soon add an http streaming parser. Maybe saving the data to a cache or memmapping would be better?

**Comment by bluemarvin** [comment]
Also, with the current implementation, the resources are loaded straight from the apk so there isn't a local file that we can reload. I think a per-run cache of the raw data might be the best approach?

**Comment by MortimerGoro** [comment]
I like the cache idea to support all the different origins

**Comment by bluemarvin** [comment]
Fixed in #25
